### ISSUE TITLE
AT_00.002.05 | New Item > Create Pipeline Project > Create Pipeline Project with correct name via side menu on the Dashboard

### ISSUE THREAD

**Issue by Eleksor** [RedRoverSchool/JenkinsQA_2024_fall#1045]
**Preconditions:**
User logged in

**Steps:**

  1. Klick on the link "+New item" in the left sidebar on the Dashbord page.
  2. Enter valid name in "Enter an item name" field
  3. Click on "Pipeline project" item
  4. Click on "ok" button
  5. Click on "save" button
  6. Check that Pipline Project was created

**Expected results:**
We are on created pipeline project's page.

**Comment by pakhomova-ev** [comment]
duplicate #889
