### ISSUE TITLE
ERR | FreestyleProject3Test | testAddDescriptionOnProjectStatusPage

### ISSUE THREAD

**Issue by pakhomova-ev** [RedRoverSchool/JenkinsQA_2024_fall#1101]
testAddDescriptionOnProjectStatusPage(school.redrover.FreestyleProject3Test)  Time elapsed: 11.259 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: description-link (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1025-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.85, chrome: {chromedriverVersion: 131.0.6778.85 (3d81e41b6f3a..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:35759}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:35759/devtoo..., se:cdpVersion: 131.0.6778.85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3e772fbf296217acb3af0fdd41f1996d
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.FreestyleProject3Test.addDescriptionOnProjectStatusPage(FreestyleProject3Test.java:37)
	at school.redrover.FreestyleProject3Test.testAddDescriptionOnProjectStatusPage(FreestyleProject3Test.java:122)

[log](https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/12050699236/job/33600113361)

**Comment by kas-113** [comment]
testAddDescriptionOnProjectStatusPage is deleted in class FreestyleProject3Test 
RF card https://github.com/orgs/RedRoverSchool/projects/3/views/1?pane=issue&itemId=89172099&issue=RedRoverSchool%7CJenkinsQA_2024_fall%7C1205
PR link
