### ISSUE TITLE
ERR | FreestyleProject3Test | testAddBuildStepsExecuteShellCommandWhenConfigureProject

### ISSUE THREAD

**Issue by pakhomova-ev** [RedRoverSchool/JenkinsQA_2024_fall#1129]
Tests run: 419, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 973.639 sec <<< FAILURE!
testAddBuildStepsExecuteShellCommandWhenConfigureProject(school.redrover.FreestyleProject3Test)  Time elapsed: 5.829 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //a[contains(@href, 'configure')] (tried for 2 second(s) with 500 milliseconds interval)
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1025-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.85, chrome: {chromedriverVersion: 131.0.6778.85 (3d81e41b6f3a..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:36603}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:36603/devtoo..., se:cdpVersion: 131.0.6778.85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b8c7f021a8e9c9b5ca535c5cf7dff9bc
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.FreestyleProject3Test.clickConfigureInSidebarMenuOnProjectStatusPage(FreestyleProject3Test.java:48)
	at school.redrover.FreestyleProject3Test.testAddBuildStepsExecuteShellCommandWhenConfigureProject(FreestyleProject3Test.java:222)

[log](https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/12056834387/job/33620176794)

**Comment by kas-113** [comment]
RF card https://github.com/orgs/RedRoverSchool/projects/3/views/1?pane=issue&itemId=89436188
PR link https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/1302
