### ISSUE TITLE
ERR |  FreestyleProject3Test | testCheckSidebarMenuItemsOnProjectStatusPage

### ISSUE THREAD

**Issue by evgnick** [RedRoverSchool/JenkinsQA_2024_fall#1181]
testCheckSidebarMenuItemsOnProjectStatusPage(school.redrover.FreestyleProject3Test)  Time elapsed: 11.344 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //span[contains(text(), 'Rename')] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1025-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.85, chrome: {chromedriverVersion: 131.0.6778.85 (3d81e41b6f3a..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:39637}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:39637/devtoo..., se:cdpVersion: 131.0.6778.85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 3e51158aa77ac212af1063e507c59d4e
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.FreestyleProject3Test.testCheckSidebarMenuItemsOnProjectStatusPage(FreestyleProject3Test.java:235)

https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/12073913453/job/33670951562?pr=1179

**Comment by kas-113** [comment]
RF card https://github.com/orgs/RedRoverSchool/projects/3/views/1?pane=issue&itemId=89361568
PR link https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/1288
