### ISSUE TITLE
US_04.001 | Folder > Rename Folder

### ISSUE THREAD

**Issue by PavelSZh** [RedRoverSchool/JenkinsQA_2024_fall#482]
Description
As a user, I want to be able to rename existing folders so that I fixed any errors or update names if needed

Acceptance Criteria:

- The user can start renaming from the main page via "Dropdown menu";
- The user can rename a folder directly from folder's page;
- The user can rename a folder from "My views" page via "Dropdown menu";
- In case the name hasn't been changes, the user sees an error page: "The new name is the same as the current name.";
- In case using unsafe characters ($, %, #, &, [, ], @, !, ~, ^, \, /, :, *, ?, ", <, >, |), the user sees an error page : "‘character’ is an unsafe character";
- If folder's name is empty the user sees an error: "No name is specified".

**Comment by NatashaShimkiv** [comment]
I think you can correct the description
like this
"As a user, I want to be able to rename existing folders so that I fixed any errors or update names if needed"

**Comment by PavelSZh** [comment]
corrected
