### ISSUE TITLE
US_04.003 | Folder > Delete Folder

### ISSUE THREAD

**Issue by PavelSZh** [RedRoverSchool/JenkinsQA_2024_fall#483]
Description
As an User I want to delete existing folders so that I can clean the system from deprecated, unnecessary or any mistakes data

Acceptance Criteria:

- The user can delete an existing folder from the main page via "Dropdown menu";
- The user can delete an existing folder directly from folder's page;
- The user can delete an existing folder directly from "My views" page via "Dropdown menu";
- The user sees "Delete folder" window once start deleting;
- The user can approve deleting in "Delete folder" window via "Yes" button;
- The user can cancel deleting in "Delete folder" window via "Cancel" button;

**Comment by NatashaShimkiv** [comment]
Hi, Pavel.

I did't understand the first point. Can you explain it?

I think this points may be at the beginning:
The user can delete an existing folder from the main page via "Dropdown menu";
The user can delete an existing folder directly from folder's page;
The user can delete an existing folder directly from "My views" page via "Dropdown menu".

You can write in fourth point about "Delete folder" window 
Like this fo example
"The user sees "Delete folder" field in Dropdown menu and at folder's page."

And then this points:
The user can approve deleting in "Delete folder" window via "OK" button;
The user can cancel deleting in "Delete folder" window via "Cancel" button;

But in my jenkins there is a button "yes", not "ok"

**Comment by PavelSZh** [comment]
Hi! 

Yes, I agree: I corrected all the points.
In first point it was about confirmation window
