### ISSUE TITLE
US_04.002 | Folder > Move Folder to Folder

### ISSUE THREAD

**Issue by PavelSZh** [RedRoverSchool/JenkinsQA_2024_fall#487]
Description
As an User I want to move folder to folder so that I can sort and organize my data and build hierarchy

Acceptance Criteria:

- The user can move folder to folder from the main page via "Dropdown menu";
- The user can move folder to folder directly from folder's page;
- The user can move folder to folder from "My views" page via "Dropdown menu";
- The user can move folder to folder which are on the same level or on the main page;
- The user can move folder to folder from lower level to upper level;
- The user can't move parent folder to child folder so there's no possibility to choose such option in dropdown menu;
- The user can't move a folder to the same place so no actions happen while pressing "Move" button.

**Comment by NatashaShimkiv** [comment]
I think this points should be in the begining
The user can move folder to folder from the main page via "Dropdown menu";
The user canmove folder to folder directly from folder's page;
The user can move folder to folder from "My views" page via "Dropdown menu".

Like in your US "Rename Folder"

**Comment by PavelSZh** [comment]
corrected
