### ISSUE TITLE
US_00.004 | New Item > Create new item from other existing

### ISSUE THREAD

**Issue by ovdro** [RedRoverSchool/JenkinsQA_2024_fall#492]
**Description:**
As a registered user, I want to create a new item from an existing one so that I can save time and maintain consistency in similar items.

**Acceptance Criteria:**

- The user can create a new item from an existing one.
- The user cannot create an item with an empty name.
- The user cannot create an item with an existing name.
- The user cannot create an item with a name containing prohibited characters.
- After creating a new item, the user can see it listed in the relevant section or view where similar items are displayed.

**Comment by NatashaShimkiv** [comment]
I think you can join the second, third and fourth point. 
Like this:
"The user can create an item with valid characters only"
And I think you can add point discribed what user see ufter he created new item from other existing, where user see this new item.

**Comment by ovdro** [comment]
I divided different types of field checks into different points, because in this form they are more atomic and verifiable
I’ll add a paragraph with a description, I agree

**Comment by ovdro** [comment]
However, I am happy to adjust as needed, although I believe the current version follows the general recommendations well.
