### ISSUE TITLE
US_01.007 | FreestyleProject > Workspace delete

### ISSUE THREAD

**Issue by ovdro** [RedRoverSchool/JenkinsQA_2024_fall#494]
**Description:**
As a registered user, I want to delete the current workspace so that I can ensure a clean environment for my next build.

**Acceptance Criteria:**

- The user can delete the current workspace, which will delete all files and folders within it.
- The user is notified that deleting the workspace is irreversible and confirms the action before proceeding.
- After deleting, the user sees the empty workspace ready for the next build.

**Comment by NatashaShimkiv** [comment]
Just a small correction in the third point

Like this, fo example.
"After deleting, user see the empty workspace ready for the next build"
