### ISSUE TITLE
US_01.008 | FreestyleProject > Build item

### ISSUE THREAD

**Issue by ovdro** [RedRoverSchool/JenkinsQA_2024_fall#498]
**Description:**
As a registered user, I want to trigger a "Build Now" action so that I can initiate an immediate build of my project.

**Acceptance Criteria:**

- The user can select the "Build Now" option to start a build manually.
- The user sees a visual indicator from a system that a build has been initiated (e.g., a progress bar or status update).
- The user can view the build's real-time progress and logs as the build runs.
- After completion, the user can see the build status (success, failure, or unstable) and any associated artifacts or reports.

**Comment by NatashaShimkiv** [comment]
The second point can be adjusted based on the user, not the technical component.

For example.
"The user see a visual indicator from system that a build has been initiated"
