### ISSUE TITLE
US_01.009 | FreestyleProject > Configure item

### ISSUE THREAD

**Issue by ovdro** [RedRoverSchool/JenkinsQA_2024_fall#499]
**Description:**
As a registered user, I want to configure an item so that I can customize its settings and ensure it builds according to my requirements.

**Acceptance Criteria:**

- The user can access the "Configure" option for an item, allowing them to modify settings.
- The user can adjust configuration parameters, such as description, source code repository, build triggers, steps, environments and post-build actions.
- The user can save configuration changes, and they are reflected in the next build.
- The user should see confirmation from the system that changes were successfully saved.

**Comment by NatashaShimkiv** [comment]
Hi, Oleksandr!
The fourth point, I think, can be adjusted a little so that it is not technical, but user-oriented.

For example
"The user should see a confirmation that changes were successfully saved."
or
"The user should see confirmation from the system that changes were successfully saved."
