### ISSUE TITLE
US_00.000 | New Item > Create New item

### ISSUE THREAD

**Issue by NatalieDi** [RedRoverSchool/JenkinsQA_2024_fall#506]
**Description:**
As a registered user, I want to create a new item in Jenkins so that I can initiate and manage different types of automation projects.

**Acceptance Criteria**
- user can create new item from the "Create a job" button on the homepage when no jobs exist.
- user can create new item from Dashboard dropdown menu.
- user can create new item from the "New Item" link in the left sidebar.
- user can use only unique item name, If the entered item name already exists, a clear error message is shown ( “Item name already exists.”)
- If no item name is entered or an invalid name is entered (special characters, spaces, etc.), a message prompts the user to enter a valid name.
- user is transferred to the configuration page for the selected item type after clicking "OK."
- user can see new item name on dashboard only after click Save button.

**Comment by NatashaShimkiv** [comment]
Excellent!
