### ISSUE TITLE
US_01.001 | Freestyle Project > Add Description

### ISSUE THREAD

**Issue by NatalieDi** [RedRoverSchool/JenkinsQA_2024_fall#513]
**Description:**
As a user with edit permissions on a Freestyle Project in Jenkins, I want to add or edit a description for my project so that team members can understand the purpose, functionality, or other important details about the Freestyle project.

**Acceptance Criteria**

- The user can access the description field:

1. When creating a new Freestyle Project.
2. By navigating to the configuration page of an existing Freestyle Project.

- After saving, the description is displayed on the project’s main page, just below the project name.

- The user can edit the description at any time and save changes, with real-time updates reflecting on the project’s main page.

- If the user clears the description field and saves it, the description is removed from the project’s main page.

**Comment by NatashaShimkiv** [comment]
Just a small correction in the second point

Like this, fo example.
"After saving, user can see the description on the project’s main page, just below the project name."
