### ISSUE TITLE
US_00.002 | New item > Create Pipeline Project

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#516]
Description:
As a registered user, I want to create a new Pipeline project in the "New Item" tab and configure it to automate a multi-stage build and deployment process to streamline workflows from commit to deployment and reduce manual errors.

Acceptance Criteria
1. The user can navigate to the "New Item" tab and create a new project by selecting the Pipeline type.
2. The user must specify a unique project name and select the "Pipeline" type.

3. After selecting the "Pipeline" type, the user is taken to the configuration page to define build stages, triggers, and post-build actions.
4. The user can save the configuration and return to the Jenkins dashboard.
5. When returning to the home page, the user should see the created pipeline project.

**Comment by NatashaShimkiv** [comment]
Hi Irina.
I think the fifth point can be adjusted a little
Like this for example
"When returning to the home page, the user should see the created pipeline project"
