### ISSUE TITLE
US_14.001 | Header > Return to the dashboard page with one click

### ISSUE THREAD

**Issue by NatalieDi** [RedRoverSchool/JenkinsQA_2024_fall#517]
**Description:**

As a user navigating Jenkins, I want to return to the dashboard page with one click to quickly access my projects and other functionalities without using the browser's back button.

**Acceptance Criteria:**

- The header must include a clearly labeled "Dashboard" link that is easily accessible from any page within Jenkins.
- Clicking the "Dashboard" link should redirect the user to the main dashboard page.
- The "Dashboard" link should be prominently displayed in the header for visibility and ease of access.
- After returning to the dashboard, the user should see the same view they had before navigating away, preserving their previous context (e.g., any filters or search results).

**Comment by NatashaShimkiv** [comment]
Hi Natalie. 
The first and third points are similar and speak more about the technical side, not about the user, I think. You can supplement the second point, and remove the first and third.
Like this for exemple
"Clicking the "Dashboard" link should redirect the user to the main dashboard page from any page within Jenkins"

**Comment by NatalieDi** [comment]
Check please, I fixed
