### ISSUE TITLE
US_04.004 | Folder > Add and edit description of the folder

### ISSUE THREAD

**Issue by PavelSZh** [RedRoverSchool/JenkinsQA_2024_fall#527]
Description
As an User I want to add and edit folder's description so that I can clarify and describe all the information about the folder

Acceptance Criteria:

- The user can add description to the folder;
- The user can edit an existing description;
- The user can see added description below folder's icon;
- The user can completely clear the description and save;
- The user can active "Preview" option below desctiption's field;
- The user can hide "Preview" option via "Hide preview" button.

**Comment by NatashaShimkiv** [comment]
Do you think it might be possible to correct the description something like this?
As a user I want to be able to add and edit a folder description so that I can clarify all the information about the folder, its purpose.

The acceptance criteria are excellent, I think!

**Comment by PavelSZh** [comment]
Hi!
Yeap, I corrected the description
