### ISSUE TITLE
US_08.003 | Build history > Use filter in build history

### ISSUE THREAD

**Issue by ovdro** [RedRoverSchool/JenkinsQA_2024_fall#533]
**Description:**
As a registered  user, I want to use filters in the build history so that I can easily find specific builds based on criteria like status, date, or build author.

**Acceptance Criteria:**

1. The user can access filter options in the Build History view to narrow down the list of builds.
2. The user can filter builds by criteria such as:
- Build status (success, failure, unstable)
- Date range
- Triggered by specific users
- Build labels or tags, if available
3. The user sees only assemblies that match the selected criteria in the filtered results.
4. The user can clear the filters to return to the full build history list.

**Comment by NatashaShimkiv** [comment]
I think the third point can be adjusted as follows:

In the filtered results, the user sees only assemblies that match the selected criteria.

**Comment by ovdro** [comment]
I agree, I’ll phrase it as follows:
3. The user sees only assemblies that match the selected criteria in the filtered results

**Comment by NatashaShimkiv** [comment]
Excellent
