### ISSUE TITLE
US_00.007 | New item > Create Organization Folder

### ISSUE THREAD

**Issue by lutsco** [RedRoverSchool/JenkinsQA_2024_fall#544]
Description
As a user, I want to create an organization folder to group projects and jobs by organization, so that I can centralize and streamline resources related to a specific organization within Jenkins.

Acceptance Criteria

* The User is able to access the "New Item" option and select "Organization Folder" from the list.
* The User is able to enter organization details, configure folder properties, and create the organization folder successfully.
* The User is able to integrate with version control systems (e.g., GitHub) to automatically pull and organize repositories under the folder based on defined criteria.
* The User is able to view and manage projects within the organization folder, maintaining a structured overview of related resources.

**Comment by NatashaShimkiv** [comment]
The same adjustments that I indicated in the comment in your US FreestyleProject > Delete Project
