### ISSUE TITLE
US_01.002 | FreestyleProject > Rename Project

### ISSUE THREAD

**Issue by lutsco** [RedRoverSchool/JenkinsQA_2024_fall#545]
Description
As a user, I want to rename a project in Jenkins, so that I can accurately reflect changes or improvements in the project's purpose.

Acceptance Criteria

* The User is able to access the project settings to initiate the renaming process.
* The User is able to enter a new name for the project and save the changes.
* The User is able to see the updated project name across all relevant Jenkins views and job references.

**Comment by NatashaShimkiv** [comment]
You describe the acceptance criteria very well, just adjust it a little according to the sample, comment in your US FreestyleProject > Delete Project
