### ISSUE TITLE
US_01.003 | FreestyleProject > Disable/Enable Project

### ISSUE THREAD

**Issue by lutsco** [RedRoverSchool/JenkinsQA_2024_fall#546]
Description
As a user, I want to disable or enable a project in Jenkins, so that I can control when a project is active or inactive based on project needs.

Acceptance Criteria
 
* The User is able to access the project configuration to disable the project, preventing it from running while maintaining its configuration.
* The User is able to view a clear indicator showing whether the project is currently enabled or disabled.
* The User is able to re-enable a disabled project, restoring its ability to run builds when needed.

**Comment by NatashaShimkiv** [comment]
The same adjustments that I indicated in the comment in US  FreestyleProject > Delete Project
