### ISSUE TITLE
US_01.004 | FreestyleProject > Delete Project

### ISSUE THREAD

**Issue by lutsco** [RedRoverSchool/JenkinsQA_2024_fall#547]
Description
As a user, I want to delete a project in Jenkins, so that I can remove irrelevant projects from the workspace and maintain an organized environment.

Acceptance Criteria

* The User is able to access the project settings to initiate the deletion process.
* The User is able to confirm the deletion of the project to prevent accidental removal.
* The User is able to remove all associated configurations, builds, and resources tied to the project from Jenkins.

**Comment by NatashaShimkiv** [comment]
Hi Michael!

After Description we write 

Acceptance Criteria

The User is able to access the project settings to initiate the deletion process.
The User is able to confirm the deletion of the project to prevent accidental removal.
The User is able to remove all associated configurations, builds, and resources tied to the project from Jenkins.

Like this
