### ISSUE TITLE
US_02.005 | Pipeline > Delete Pipeline

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#557]
**Description:**
As a registered user, I want to delete an existing pipeline project when it is no longer needed so that I can keep the Jenkins environment organized and free of unused projects.

**Acceptance Criteria:**

1. The user can select the "Delete Pipeline" option from the pipeline menu to remove the project from Jenkins.
2. When the user initiates the deletion process, a confirmation prompt appears to prevent accidental deletion.
3. The user must confirm the deletion action to proceed.
4. The user can see that the project is no longer displayed in the Jenkins dashboard or in the pipeline list.

**Comment by NatashaShimkiv** [comment]
In description should be phrase "so that i"
Correct, please.
I think the fourth point can be removed.
The fifth point can be fixed

The user can see that the project is no longer displayed in the Jenkins dashboard or in the pipeline list.
