### ISSUE TITLE
US_16.002 | Dashboard > Create view

### ISSUE THREAD

**Issue by Natashki** [RedRoverSchool/JenkinsQA_2024_fall#595]
As a registered user, I want to be able to create views in the dashboard so that I can combine similar projects under one description and better organize my workspace

Acceptance criteria:

- The user can create a new view by selecting specific columns, filters, and sort orders within the dashboard.
- The user can create a personal view
- When creating a new view, the user is prompted to name the view.
- View names must be unique and descriptive to help the user identify saved views.

**Comment by NatashaShimkiv** [comment]
In Description should be the purpose of creating view from the user’s point.
Why do they need to create a view? I guess the answer would be something like “so that I can combine similar projects under one description and better organize my workspace”
