### ISSUE TITLE
US_16.001 | Dashboard > Sort Items

### ISSUE THREAD

**Issue by Natashki** [RedRoverSchool/JenkinsQA_2024_fall#596]
As a registered user, I want to be able to sort items in the dashboard table by columns: status, weather, name, last success, last failure and last duration, so I can easily organize and analyse information.

Acceptance Criteria:

- The user can click on any column header (status, weather, name, last success, last failure, last duration) to sort the table by that column.
- The user can click on a column header to switch the sort order from ascending to descending
- By default, the table should be sorted by Name ascending
- Save sorting when user leave  dashboard and return to it

**Comment by NatashaShimkiv** [comment]
Everything is fine, the only room for improvement I could see here is to rephrase the second point. 
Like this for example
"The user can click on a column header to switch the sort order from ascending to descending"
