### ISSUE TITLE
US_02.007 | Pipeline > Rename

### ISSUE THREAD

**Issue by IrinaNap** [RedRoverSchool/JenkinsQA_2024_fall#625]
**Description:**
As a registered user, I want to rename my existing pipeline project so that I can update it to better reflect its purpose or scope.

**Acceptance Criteria:**

1. The user can go to the Rename section and enter a new name for the project.
2. If the new name is the same as the current name, the system displays a warning and does not allow the change to be saved.
3. After successfully renaming, user can see new name is displayed across all Jenkins pages related to this project.
4. The change log should record the project renaming for future tracking.

**Comment by NatashaShimkiv** [comment]
Everything is fine, the only room for improvement I could see here is to rephrase the third point.

Like this for example
After successfully renaming, user can see new name is displayed across all Jenkins pages related to this project.
