### ISSUE TITLE
US_15.001 | Nodes > Create new node

### ISSUE THREAD

**Issue by Eduard-QA** [RedRoverSchool/JenkinsQA_2024_fall#735]
**Description**

 1. As a registered and authorized user, I want to be able to create one or more agents so that I can automatically build, test, and deploy my application to different build environments, and also distribute the load between agents running in parallel

**Ensure the User able to:**

- user will be able to create a new agent by selecting “Nodes” on the “Manage Jenkins” page.
- user can start creating an agent by selecting the option "New Node"
- user can create a node by filling in the required fields and checkboxes with valid values.

> - Name                                                                                                                 
> - Remote root directory
> - Host (if the appropriate connection option is selected)

- user can see the created node in the list on the "Nodes" page

**Comment by NatashaShimkiv** [comment]
Everything is fine, just a couple of points that I wanted to draw attention to.
In the description, you need to indicate the need that the user satisfies with this feature. The wording should include the phrase "so that i can..."

**Comment by Eduard-QA** [comment]
> Everything is fine, just a couple of points that I wanted to draw attention to. In the description, you need to indicate the need that the user satisfies with this feature. The wording should include the phrase "so that i can..."

Fixed
