### ISSUE TITLE
US_15.002 | Nodes > Delete node

### ISSUE THREAD

**Issue by Eduard-QA** [RedRoverSchool/JenkinsQA_2024_fall#736]
**Description**

1. As a registered and authorized user, I want to be able to delete a previously created and currently unused node so that I can keep the system more efficient, secure, and organized.

**Ensure the User able to:**  

- click on the "Delete Agent" link:

> - the pop-up menu next to the node name in the node list 
> - the pop-up menu next to the node icon in the " Build Executor Status " section 
> - the left menu on the "configuration" page

- After clicking on the link, the user should receive a pop-up window asking to confirm the deletion
- After confirming the deletion, the user can verify that the node name has disappeared from the list

**Comment by NatashaShimkiv** [comment]
A little clarification is needed in the description as in the user story 15.001

**Comment by Eduard-QA** [comment]
> A little clarification is needed in the description as in the user story 15.001

Fixed
