### ISSUE TITLE
ERR_005 | FreestyleProject3Test | testCheckSidebarMenuItemsOnProjectStatusPage

### ISSUE THREAD

**Issue by AnnaLimutina** [RedRoverSchool/JenkinsQA_2024_fall#849]
testCheckSidebarMenuItemsOnProjectStatusPage(school.redrover.FreestyleProject3Test)  Time elapsed: 11.259 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //span[contains(text(), 'Rename')] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1025-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.69, chrome: {chromedriverVersion: 131.0.6778.69 (77e2244bbcda..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:38993}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:38993/devtoo..., se:cdpVersion: 131.0.6778.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9d44f38c1aca32296c3e112e2d1b483e
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.FreestyleProject3Test.testCheckSidebarMenuItemsOnProjectStatusPage(FreestyleProject3Test.java:241)

**Comment by kas-113** [comment]
Err005 changed expected conditions in create method
