### ISSUE TITLE
TC_00.000.06 | New Item > Create New item > Create new item from the "New Item" link in the left sidebar.

### ISSUE THREAD

**Issue by DmitriiRusak** [RedRoverSchool/JenkinsQA_2024_fall#877]
Description:

User can create new item from the "New Item" link in the left sidebar.
Preconditions:

The user is registered in the system with the valid login and password
The main page of “Jenkins” has been loaded
Steps:

Click the "New Item" link in the left sidebar
Enter “NewItemName” in the name field
Click on the project type "Freestyle project"
Click on the "OK" button
Click on "Jenkins" (logo) to go to the main page
Check that the table has an entry named “NewItemName”
Expected results:

Item named “NewItemName” has been found

**Comment by NatashaShimkiv** [comment]
Hi, Dmitrii! Unfortunately, such a TC has already been written before. I see that you have not written a AT yet, please choose another feature  for writing a TC.
