### ISSUE TITLE
ERR_013 | FreestyleProject3Test | testDeleteProjectViaSidebarMenuOnProjectStatusPage

### ISSUE THREAD

**Issue by AnnaLimutina** [RedRoverSchool/JenkinsQA_2024_fall#886]
testDeleteProjectViaSidebarMenuOnProjectStatusPage(school.redrover.FreestyleProject3Test)  Time elapsed: 5.738 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //a[@data-title='Delete Project'] (tried for 2 second(s) with 500 milliseconds interval)
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1025-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.69, chrome: {chromedriverVersion: 131.0.6778.69 (77e2244bbcda..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:39369}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:39369/devtoo..., se:cdpVersion: 131.0.6778.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 53ceeb2921f8a53f041438dee69f31ec
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.FreestyleProject3Test.testDeleteProjectViaSidebarMenuOnProjectStatusPage(FreestyleProject3Test.java:373)

**Comment by kas-113** [comment]
getWait2() changed for  getWait10()
